"""add category field to merch model

Revision ID: 33e97f3a2c00
Revises: 20260209_job_vacancies_image
Create Date: 2026-02-17 06:42:00.641330

"""
from alembic import op
import sqlalchemy as sa


revision = '33e97f3a2c00'
down_revision = '20260209_job_vacancies_image'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merches', sa.Column('category', sa.String(length=50), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE merches SET category = 'equipment' WHERE category IS NULL")
    
    # Make column NOT NULL after setting values
    op.alter_column('merches', 'category', existing_type=sa.String(length=50), nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merches', 'category')
    # ### end Alembic commands ###
