"""make merches owner_id nullable

Revision ID: 340472ffc715
Revises: bd385025e69f
Create Date: 2026-01-18 16:14:02.922531

"""
from alembic import op
import sqlalchemy as sa


revision = '340472ffc715'
down_revision = 'bd385025e69f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merches', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('merches_owner_id_fkey', 'merches', type_='foreignkey')
    op.create_foreign_key(None, 'merches', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merches', type_='foreignkey')
    op.create_foreign_key('merches_owner_id_fkey', 'merches', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('merches', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
