"""add rating field to users table

Revision ID: 831ea86b0a6b
Revises: 33e97f3a2c00
Create Date: 2026-02-18 05:08:12.477844

"""
from alembic import op
import sqlalchemy as sa


revision = '831ea86b0a6b'
down_revision = '33e97f3a2c00'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE users SET rating = 4.5 WHERE rating IS NULL")
    
    # Make column NOT NULL after setting values
    op.alter_column('users', 'rating', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
