"""make news author_id nullable

Revision ID: bd385025e69f
Revises: 
Create Date: 2026-01-18 16:06:42.897879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bd385025e69f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_chats', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_chats', 'is_user_message',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('ai_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_chats_id'), 'ai_chats', ['id'], unique=False)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'merch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('cart', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cart', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.alter_column('education', 'region',
               existing_type=postgresql.ENUM('ANDIJAN', 'BUKHARA', 'FERGANA', 'JIZZAKH', 'KARAKALPAKSTAN', 'KASHKADARYA', 'KHOREZM', 'NAMANGAN', 'NAVOIY', 'SAMARKAND', 'SURKHANDARYA', 'SYRDARYA', 'TASHKENT_CITY', 'TASHKENT_REGION', name='region'),
               nullable=False)
    op.alter_column('education', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('education', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'merch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('favorites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.alter_column('job_vacancies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('job_vacancies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_vacancies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_job_vacancies_id'), 'job_vacancies', ['id'], unique=False)
    op.alter_column('merches', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('merches', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('merches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_merches_id'), 'merches', ['id'], unique=False)
    op.alter_column('news', 'category',
               existing_type=postgresql.ENUM('FOOTBALL', 'BOXING', 'WRESTLING', 'TENNIS', 'BASKETBALL', 'SWIMMING', 'GENERAL', name='newscategory'),
               nullable=False,
               existing_server_default=sa.text("'GENERAL'::newscategory"))
    op.alter_column('news', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('news', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('news_slug_key', 'news', type_='unique')
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    op.drop_constraint('news_author_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'users', ['author_id'], ['id'])
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('PURCHASE', 'DONATION', 'SUBSCRIPTION', name='transactiontype'),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'ATHLETE', 'TRAINER', 'OBSERVER', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'OBSERVER'::userrole"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'ATHLETE', 'TRAINER', 'OBSERVER', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'OBSERVER'::userrole"))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('PURCHASE', 'DONATION', 'SUBSCRIPTION', name='transactiontype'),
               nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_author_id_fkey', 'news', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.create_unique_constraint('news_slug_key', 'news', ['slug'])
    op.alter_column('news', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('news', 'category',
               existing_type=postgresql.ENUM('FOOTBALL', 'BOXING', 'WRESTLING', 'TENNIS', 'BASKETBALL', 'SWIMMING', 'GENERAL', name='newscategory'),
               nullable=True,
               existing_server_default=sa.text("'GENERAL'::newscategory"))
    op.drop_index(op.f('ix_merches_id'), table_name='merches')
    op.alter_column('merches', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merches', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('merches', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_job_vacancies_id'), table_name='job_vacancies')
    op.alter_column('job_vacancies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_vacancies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_vacancies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.alter_column('favorites', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('favorites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('favorites', 'merch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.alter_column('education', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('education', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('education', 'region',
               existing_type=postgresql.ENUM('ANDIJAN', 'BUKHARA', 'FERGANA', 'JIZZAKH', 'KARAKALPAKSTAN', 'KASHKADARYA', 'KHOREZM', 'NAMANGAN', 'NAVOIY', 'SAMARKAND', 'SURKHANDARYA', 'SYRDARYA', 'TASHKENT_CITY', 'TASHKENT_REGION', name='region'),
               nullable=True)
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.alter_column('cart', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cart', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cart', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('cart', 'merch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_ai_chats_id'), table_name='ai_chats')
    op.alter_column('ai_chats', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chats', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chats', 'is_user_message',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('ai_chats', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
